vim.keymap.set("n", "<Space>", "<Nop>", { silent = true })
vim.g.mapleader = " "
vim.keymap.set("n", "<C-z>", "")
vim.keymap.set("n", "<C-s-z>", "")
vim.keymap.set("n", "<C-S>", "<cmd>w<CR>", { desc = "Save document" })
vim.keymap.set("n", "fg", "<cmd>Telescope git_files<CR>", { desc = "Telescope find git files" })
vim.keymap.set("n", "fd", "<cmd>Telescope find_files<CR>", { desc = "Telescope find files" })
vim.keymap.set("n", "ff", "<cmd>Telescope<CR>", { desc = "Open Telescope" })
vim.keymap.set("n", "<leader>e", "<cmd>Neotree focus<CR>", { desc = "Focus NvimTree" })
vim.keymap.set("n", "<C-n>", "<cmd>Neotree toggle<CR>", { desc = "Toggle NvimTree" })
vim.keymap.set("n", "<leader><tab>", "<cmd>bnext<CR>", { desc = "Next buffer" })
vim.keymap.set("n", "<leader><s-tab>", "<cmd>bprev<CR>", { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>x", "<cmd>lua require('close_buffers').delete({type='this'})<CR>", { desc = "Close current buffer" })
